# Generated by Django 3.1.7 on 2021-03-21 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('registration_no', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('region', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('sub_county', models.CharField(max_length=50)),
                ('post_code', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('ownership', models.CharField(max_length=50)),
                ('parish', models.CharField(max_length=50)),
                ('fax', models.CharField(max_length=50)),
                ('tin', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to=None)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companys',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('GS', 'PMS(Gasoline)'), ('DS', 'AGO(Diesel)'), ('KS', 'BIK(Keresone)'), ('EO', 'Engine Oil'), ('JF', 'Jet Fuel'), ('FO', 'Furnance Oil')], max_length=50)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Sample',
                'verbose_name_plural': 'Samples',
            },
        ),
        migrations.CreateModel(
            name='SampleRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=50, unique=True)),
                ('registration_date', models.DateField()),
                ('representative', models.CharField(max_length=50)),
                ('report_date', models.CharField(max_length=50, verbose_name='Expected Report Date')),
                ('remarks', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
            options={
                'verbose_name': 'SampleRequest',
                'verbose_name_plural': 'SampleRequests',
            },
        ),
    ]
