# Generated by Django 3.2 on 2021-05-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinspection',
            old_name='check_list_no',
            new_name='inspection_no',
        ),
    ]
