# Generated by Django 3.2 on 2021-05-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_check_list_no_companyinspection_inspection_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas',
            name='company',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
            preserve_default=False,
        ),
    ]
