# Generated by Django 3.1.7 on 2021-03-27 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_samplerequest_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplerequest',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(choices=[('GS', 'PMS(Gasoline)'), ('DS', 'AGO(Diesel)'), ('KS', 'BIK(Keresone)'), ('EO', 'Engine Oil'), ('JF', 'Jet Fuel'), ('FO', 'Furnance Oil')], max_length=150),
        ),
        migrations.AlterField(
            model_name='samplerequest',
            name='registration_date',
            field=models.DateField(null=True),
        ),
    ]
