# Generated by Django 3.1.7 on 2021-05-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gas_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field_enforcement',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='is_responded_to',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='field_enforcement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
