# Generated by Django 3.1.7 on 2021-05-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210512_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectionchecklist',
            old_name='company_inspection',
            new_name='inspection_no',
        ),
    ]
