# Generated by Django 3.1.7 on 2021-05-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210512_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectionchecklist',
            old_name='checkList',
            new_name='checklist',
        ),
    ]
