# Generated by Django 3.1.7 on 2021-04-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210404_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='parameter',
            field=models.CharField(choices=[('mk', 'Marker'), ('DS', 'Density')], max_length=20),
        ),
    ]
