# Generated by Django 3.1.7 on 2021-05-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210512_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectionchecklist',
            old_name='inspection_no',
            new_name='inspection',
        ),
    ]
