# Generated by Django 3.2 on 2021-04-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_logo_company_logos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='logos',
            new_name='logo',
        ),
    ]
