# Generated by Django 3.2 on 2021-04-11 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_logos_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='fuel_type',
            field=models.CharField(choices=[('PMS(Gasoline)', 'PMS(Gasoline)'), ('DS', 'AGO(Diesel)'), ('KS', 'BIK(Keresone)'), ('EO', 'Engine Oil'), ('JF', 'Jet Fuel'), ('FO', 'Furnance Oil')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity(mls)'),
        ),
        migrations.CreateModel(
            name='NemaCertifcate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(max_length=25, verbose_name='NEMA Certificate No.')),
                ('create_date', models.DateField()),
                ('audit_due_date', models.DateField()),
                ('project', models.CharField(max_length=50)),
                ('project_purpose', models.TextField()),
                ('received_date', models.DateField()),
                ('certifcate_one', models.FileField(upload_to='')),
                ('certifcate_two', models.FileField(upload_to='')),
                ('certifcate_three', models.FileField(upload_to='')),
                ('status', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
    ]
