# Generated by Django 3.2 on 2021-04-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210411_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nemacertifcate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
