# Generated by Django 3.2 on 2021-04-21 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_nemacertifcate_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_number',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('female', models.PositiveIntegerField(max_length=200)),
                ('male', models.PositiveIntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Field_enforcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('seal_number_placed_on_nozzle', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200, unique=True)),
                ('truck_number', models.CharField(blank=True, max_length=200, null=True)),
                ('subcounty', models.CharField(max_length=200, verbose_name='Subcounty/Divison/Municipality')),
                ('seal_placed_on', models.CharField(blank=True, max_length=200, null=True, verbose_name='Seal Number(s) placed on underground tanks ')),
                ('illegal_operation', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='Continuous illegal operation of petroleum facility')),
                ('illegal_construction', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='Continuous illegal construction of petroleum facility')),
                ('Adulteraon_fuel', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='Adulteraon of fuel')),
                ('continuous_operation', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='Continuous operation without carrying out annual EIA audit')),
                ('illegal_operation_business', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='Continuous illegal operation and construction in front of congested business premises ')),
                ('illegal_operation_power_line', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='Continuous illegal operation and construction under high voltage power transmission line  ')),
                ('illegal_operation_dangerous_corner', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='Continuous illegal operation and construction in a dangerous corner  ')),
                ('illegal_operation_reserve_area', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='Continuous illegal operation and construction in a road reserve area  ')),
                ('illegal_operation_bypassing_seals', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='Continuous illegal operation aer breaking and/ or bypassing seals  ')),
                ('already', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='Already has knowledge of requirement to obtain POL & PCP  ')),
                ('facility_standards', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='Continuous illegal operation and construction which does not meet petroleum facility standards  ')),
                ('Social_aspects', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='Social aspects involving facility ')),
                ('facility_operator', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='Misrepresentaon of branding by facility operator ')),
                ('Impersonaon', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name="Impersonaon by using another's license / permit  ")),
                ('displaying_license', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='Continuous illegal operation and /or construction without displaying license /permit from MEMD  ')),
                ('uganda_police', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='Continuous illegal operation aer having been reported to uganda police  ')),
                ('land_plot_size', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='Continuous illegal operation and construction on inadequate land plot size (show size )')),
                ('under_reference', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='Continuous illegal operation and / or construction reported to uganda police under reference')),
                ('inadequate_size_land', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='Continuous illegal operation and / or construction using a POL and PCP respecvely on an inadequate size of land')),
                ('others', models.CharField(default=[('Yes', 'Yes'), ('No', 'No')], max_length=200)),
                ('remarks', models.TextField(max_length=200)),
                ('name_of_inspector', models.TextField(max_length=200)),
                ('Name_Dealer', models.CharField(max_length=200, verbose_name='Name of Dealer / Representave')),
            ],
        ),
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(choices=[('North', 'North'), ('South', 'South')], max_length=200)),
                ('latitude1', models.CharField(max_length=200)),
                ('latitude2', models.CharField(max_length=200)),
                ('latitude3', models.CharField(max_length=200)),
                ('longitude', models.CharField(choices=[('east', 'east'), ('west', 'west')], max_length=200)),
                ('longitude1', models.CharField(max_length=200)),
                ('longitude2', models.CharField(max_length=200)),
                ('longitude3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('construction_permit', models.CharField(max_length=200, verbose_name='Construction Permit Number')),
                ('operation_permit', models.CharField(max_length=200, verbose_name='Operating License Number')),
                ('TIN', models.CharField(max_length=200, verbose_name='Company Tax identification Number')),
            ],
        ),
        migrations.CreateModel(
            name='Petro_product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('PMS', 'PMS'), ('AGO', 'AGO'), ('BIK', 'BIK'), ('LPG', 'LPG'), ('OTHERS', 'OTHERS')], max_length=200)),
                ('tank_dtails', models.CharField(max_length=200)),
                ('stock', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Field_inspection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(choices=[('main', 'main'), ('sub', 'sub')], max_length=200)),
                ('plot_size', models.CharField(max_length=200, verbose_name='Plot size(at least 100*100ft) in feet')),
                ('director', models.TextField(max_length=200, verbose_name='Name and address of director')),
                ('manager', models.TextField(max_length=200, verbose_name='Name and address of manager')),
                ('type_of_facility', models.CharField(choices=[('Depot', 'Depot'), ('Truck', 'Truck'), ('Service', 'Service'), ('Filling Station', 'Filling Station')], max_length=200)),
                ('supplier_name', models.CharField(choices=[('oilcom namanve', 'oilcom namanve'), ('gaz munyoyo', 'gaz munyoyo'), ('hass bunga', 'hass bunga'), ('oryx gaba', 'oryx gaba')], max_length=200)),
                ('distance_license', models.TextField(max_length=200, verbose_name='Distance from Nearest licensed petroliem Facility')),
                ('waste_procedure', models.TextField(max_length=200, verbose_name='Procedure for handling contaminated products and wastes on the facility')),
                ('attachment', models.ImageField(blank=True, null=True, upload_to=None)),
                ('date', models.DateField(null=True)),
                ('checklist_no', models.CharField(max_length=200, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
    ]
