# Generated by Django 3.2 on 2021-04-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210427_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LPG_prices', models.PositiveIntegerField(max_length=150)),
                ('LPG_item', models.CharField(max_length=150)),
                ('LPG_Description', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='products',
            old_name='tank_dtails',
            new_name='tank_details',
        ),
        migrations.RemoveField(
            model_name='company',
            name='waste',
        ),
        migrations.AddField(
            model_name='inspection',
            name='assessment_certificate',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part1',
            field=models.CharField(default=0, max_length=200, verbose_name='Possession of certificate of approval of Environment Impact Assessment Certificate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part10',
            field=models.CharField(default=0, max_length=200, verbose_name='Identify use of inflammable material and any other source of fire on facility'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part11',
            field=models.CharField(default=0, max_length=200, verbose_name='Fire Assembly Point Clearly Labeled'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part13',
            field=models.CharField(default=0, max_length=200, verbose_name='At least one well-maintained 9-Kg Powder fire extinguisher per Pump Island'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part14',
            field=models.CharField(default=0, max_length=200, verbose_name='Availability of Sand Buckets to handle spilage accidents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part15',
            field=models.CharField(default=0, max_length=200, verbose_name='Is Safety training conducted for employees'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part16',
            field=models.CharField(default=0, max_length=200, verbose_name='Availability of Safety Signs (No smoking,Switch off engine,switch-off Mobile Phone)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part17',
            field=models.CharField(default=0, max_length=200, verbose_name='Availability of well-stocked first aid box in accordance to the factory act'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part18',
            field=models.CharField(default=0, max_length=200, verbose_name='Is there a pump in road reserve'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part19',
            field=models.CharField(default=0, max_length=200, verbose_name='Well-Constructed Perimeter Fence (at least 1.8 meters)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part2',
            field=models.CharField(default=0, max_length=200, verbose_name='Possession of a well-designed interceptor on site to control water pollution from accidental spills that could be washed off by storm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part20',
            field=models.CharField(default=0, max_length=200, verbose_name='Well-Maintained Office Block'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part21',
            field=models.CharField(default=0, max_length=200, verbose_name='Status of Canopy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part22',
            field=models.CharField(default=0, max_length=200, verbose_name='Status of Forecourt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part23',
            field=models.CharField(default=0, max_length=200, verbose_name='Status of Power'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part24',
            field=models.CharField(default=0, max_length=200, verbose_name='Adequate Lighting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part25',
            field=models.CharField(default=0, max_length=200, verbose_name='Status of Electrical Installations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part26',
            field=models.CharField(default=0, max_length=200, verbose_name='Availability of standard product off loading Point'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part27',
            field=models.CharField(default=0, max_length=200, verbose_name='Status of over-all layout and type(s) of storage tanks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part28',
            field=models.CharField(default=0, max_length=200, verbose_name='Availability of leak detection method on Any tank above 30.000m'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part29',
            field=models.CharField(default=0, max_length=200, verbose_name='Vapour venting from storage tanks (3m high)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part3',
            field=models.CharField(default=0, max_length=200, verbose_name='Possession of a standby generator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part30',
            field=models.CharField(default=0, max_length=200, verbose_name='Schedule and procedure for inspection and cleaning of vent wire gauze'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part31',
            field=models.CharField(default=0, max_length=200, verbose_name='Tanks should be clearly marked on top with the capacity written and each tank with its own calibrated dipstick'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part34',
            field=models.CharField(default=0, max_length=200, verbose_name='Are there a lot of spillage around the pump area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part35',
            field=models.CharField(default=0, max_length=200, verbose_name='Inspection requirements for compressors in accordance with the factory act'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part36',
            field=models.CharField(default=0, max_length=200, verbose_name='Inspection requirements for compressors in accordance with the factory act'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part37',
            field=models.CharField(default=0, max_length=200, verbose_name='Mechanism of waste product disposal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part38',
            field=models.CharField(default=0, max_length=200, verbose_name='Proper Drainage system for surface and foul water'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part39',
            field=models.CharField(default=0, max_length=200, verbose_name='Status of sanitation facilities for staff and customers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part4',
            field=models.CharField(default=0, max_length=200, verbose_name='Possession of a standby generator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part40',
            field=models.CharField(default=0, max_length=200, verbose_name='Standard of cleanliness within the petrol filling or service station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part41',
            field=models.CharField(default=0, max_length=200, verbose_name='Parking space. One car parking space per 4m3 floor space of the store shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part42',
            field=models.CharField(default=0, max_length=200, verbose_name='Price display Board with correct information'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part43',
            field=models.CharField(default=0, max_length=200, verbose_name='Is Information required by the NPIS availed regularly and reconcile with the information with the Ministry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part5',
            field=models.CharField(default=0, max_length=200, verbose_name='Possession of a standby generator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part6',
            field=models.CharField(default=0, max_length=200, verbose_name='Illuminated retro reflective Sign Post Visible from a distance of at least 50m'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part7',
            field=models.CharField(default=0, max_length=200, verbose_name='Emergency Telephone contact Displayed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part8',
            field=models.CharField(default=0, max_length=200, verbose_name='Proximity to household and High Voltage Supply'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='part9',
            field=models.CharField(default=0, max_length=200, verbose_name='Identify use of inflammable material and any other source of fire on facility'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='waste',
            field=models.CharField(default=0, max_length=200, verbose_name='Procedure for Handling Conterminated Wastes and Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('PMS', 'PMS'), ('AGO', 'AGO'), ('BIK', 'BIK'), ('OTHERS', 'OTHERS')], max_length=200),
        ),
        migrations.CreateModel(
            name='ProductPrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_prices', models.CharField(max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products')),
            ],
        ),
    ]
