# Generated by Django 3.2 on 2021-04-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210428_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='distance',
            field=models.CharField(max_length=100, null=True, verbose_name='Distance from Nearest Licensed Station.'),
        ),
    ]
