# Generated by Django 3.2 on 2021-05-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_company_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_prices',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='female',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='male',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gas',
            name='LPG_prices',
            field=models.PositiveIntegerField(),
        ),
    ]
